# Site settings
title: jeroenthora.be
description: Development blog of Jeroen Thora
url: "https://jeroenthora.be"

# Build settings
excerpt_separator: <!--more-->
permalink: /post/:title

# Prism.js is used for code highlight
highlighter: none
kramdown:
  syntax_highlighter_opts:
    disable : true

plugins:
  - jekyll-feed
