# Site settings
title: jeroenthora.be
description: Development blog of Jeroen Thora
url: "https://jeroenthora.be"

# Build settings
excerpt_separator: <!--more-->
permalink: /post/:title

plugins:
  - jekyll-feed
